apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: task-manager
type: Opaque
stringData:
  MONGO_URI: mongodb://task-manager:task%40123@mongo-service:27017/task-manager?authSource=task-manager

