apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: task-manager  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      automountServiceAccountToken: false  # Fix #1
      containers:
        - name: mongo
          image: mongo:8.0
          ports:
            - containerPort: 27017
          resources:  # Fix #2
            requests:
              cpu: "250m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "500m"
              memory: "1Gi"
              ephemeral-storage: "2Gi"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom: 
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME    
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc      

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: task-manager
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
